services:

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth

    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-service

    ports:
      - "8083:8083"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      BANK_SECURITY_SECRET: minha-chave-jwt-super-segura-com-mais-de-32-caracteres
      BANK_SECURITY_EXPIRATION: 86400000

    depends_on:
      - postgres-auth

volumes:
  postgres-auth-data: